# Generated by Django 5.1.1 on 2024-09-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_imagen_producto_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='foto',
            new_name='imagen',
        ),
    ]
